### ISSUE TITLE
how domain specific is this language?

### ISSUE THREAD

**Issue by stigmergic** [backspaces/agentscript#28]
```
model.turtles.with(t => t.id>10).ask(t => t.heading=0)
)


function forward(val) { this.forward(val) }

askWithBind(f) {
  return ask(t => f.bind(t)(t))
}

model.turtles.askWithBind( function () {
forward(100)

}
```

**Comment by stigmergic** [comment]
What do we do about javascript netlogo differences?

**Comment by backspaces** [comment]
The difference most glaring currently is euclidean vs heading and degrees vs radians. From slack:

Notes on degrees/radians/heading/euclidean & JavaScript/NetLogo differences
* Currently AS angles are euclidean radians everywhere 
  other than an experiment or two
  * 2D Models (theta) & 3D Models (Three.js's Object3D)
  * 2D & 3D Views use that data as well
* As Stephen says, I started looking into ways to let modelers use NL's style
  * euclidean (0 x-axis, degrees CCW, math-y) vs
    heading (0 up/y-axis, degrees CW)
  * degrees vs radians & CW/CCW degrees
* It was plagued with subtle problems, and other work took priority, 
  mainly 3D which introduced even more issues. 
  Even DataSets have "aspect" in radians!
* There is some confusion due to the experiments, "heading" for example
  * I think we should remove the experiments, providing helpers instead. 
    Awkward but less confusing
* This is important, we need quick resolution.

So the key is to remove the experiments, then decide how we want to proceed.

**Comment by backspaces** [comment]
Here are the getters/setters for Object3D used in Turtle3D:

![Snap 02 11 21-12 59 40](https://user-images.githubusercontent.com/124366/107700410-af6b8f00-6c74-11eb-8141-b62fcb29c9cc.jpg)

**Comment by backspaces** [comment]
@stigmergic See #31 Should I close this in favor of it? Or are there other domain specific issues?

**Comment by backspaces** [comment]
I think this was discussed enough to close. We can refer to this for more concrete discussions.
