### ISSUE TITLE
Mouse model complains if my world is not square

### ISSUE THREAD

**Issue by stigmergic** [backspaces/agentscript#54]
![MouseModel 2021-05-23T03_24_20 505Z](https://user-images.githubusercontent.com/202704/119247080-20f48c80-bb44-11eb-864c-5da97ed17b22.png)

I took the mouse model and set the world options as follows: 
```{minX: 1, maxX: 9, minY: 1, maxY: 5}```

This pebble causes an error:
```
agentscript.js:4163 Uncaught Error: World patchSize: x/y sizes differ 64.55555555555556, 64.6
    at World.patchSize (agentscript.js:4163)
    at Mouse.setXY (agentscript.js:36459)
    at Mouse.generalHandler (agentscript.js:36442)
    at Mouse.handleMouseUp (agentscript.js:36451)
    at HTMLBodyElement.Mouse.mouseUp (agentscript.js:36411)
```

No weeoe when I specify a square world.

I would like to set the world to be twice as wide as it is high.

**Comment by stigmergic** [comment]
AHH shucks pebble did not survive github resize.

**Comment by backspaces** [comment]
Gaak! I think this is yet another case of needing to use an "epsilon" that would catch this. I'll grab the one we use for error management. I can see it now: 

`util.closeEnough(x,y,epsilon = 1e-5)`

**Comment by backspaces** [comment]
I can't reproduce using AS.
I thought it might be due to not having a constructor, letting it fall thru to super (Model.js). Nope.
I ran it with your parameters, no error.

I did a bit of reorganizing of views2/mouse.html:
- Use models/MouseModel.js rather than the earlier in the html file.
- Tried a couple of worldOptions rather than the modeler's default, worked fine.

You can see these in the most recent commit.

**Comment by backspaces** [comment]
@stigmergic Is this still a problem?
