### ISSUE TITLE
Is there a way to run a model headless through node?

### ISSUE THREAD

**Issue by CarrKnight** [backspaces/agentscript#70]
I just wanted to try and run a model multiple times just by calling `node`.
Is there an example on how to do it?

So far for commands like these:
```
import {Model} from 'agentscript';
```
I just get a bunch of  "ReferenceError: document is not defined" when called through `node`.

Is there a different approach to achieve the same task?

**Comment by backspaces** [comment]
The difficulty with node is their requirements for importing modules, which all models are. There is the ".mjs" extension requirement which is not so bad but it runs into conflicts with importing .js dependencies.

My solution has been to use Deno which has none of those issues and we use testing our 3D extension. Here's our package.json script:

> "test3d": "deno test test/geom.js",

(The "test" command uses deno as a nice test facility w/o the bloat of many of the popular test frameworks!)

And here is a tiny "runner" of the HelloModel.js using deno which runs the model 500 times and reports a random sample of the results. The file name is hellodeno.js, and is run by:

> deno run hellodeno.js

```
import * as util from 'https://code.agentscript.org/src/utils.js'
import HelloModel from 'https://code.agentscript.org/models/HelloModel.js'

async function run() {
    console.log(`Running for 500 steps. Takes a while!`)

    const model = new HelloModel()
    await model.startup()
    model.setup()
    await util.timeoutLoop(() => {
        model.step()
    }, 500)

    const sample = util.sampleModel(model)
    console.log(sample)
}
run()
```

Would using deno be ok for you? If so I could include a deno model-runner in the repo. If not, let me see if I can tame node to be not so awkward with imports, especially remote imports like the two above.

**Comment by CarrKnight** [comment]
Thanks!

Not familiar with deno; i'll give it a spin!

**Comment by backspaces** [comment]
You're welcome!
If you have time, let us know your "workflow". I.e.
- Do you want to have a local version of agentscript via github?
- Would you prefer a simpler setup that let you write models and their views locally but get at agentscript remotely?
- How do you want to handle views? (models and views are separate for some interesting reasons)
- ..etc

I ask because we're at a point where we've finished most of the core agentscript functionality and are somewhat undecided what is the best next steps. An IDE would be great but it's a fairly tall task. We use the demo models/views as documentation which helps. Will you be deploying models for others, or mainly yourself.

So it'd be nice to know what folks actually want to do with agentscript! No worries, "I'm just playing around with a new thing" is a fine answer!

**Comment by CarrKnight** [comment]
Thanks for the quick reply. Got it running with deno in no time.

I am mostly just experimenting with tools. I usually build ABMs in Java but wanted something interactive users could play with from browser. 
All the suggested "workflows" sounds cool expansions but I think all _I_ needed was the possibility of running the model headless for parameter sweeps and maybe even optimization at some point. Looks like that's covered, so that's great.

Keep up the great work!~
