### ISSUE TITLE
add atEdge condition to let the agent keep going

### ISSUE THREAD

**Issue by m0ose** [backspaces/agentscript#77]
There does not seem to be an atEdge condition to let the agent continue off into space forever. https://github.com/backspaces/agentscript/blob/master/src/Turtle.js#L174-L180

Maybe it could be called 'nothing' or 'continue'?

**Comment by backspaces** [comment]
Hi! I tryed the 'OK' atEdge condition and it works!

>             model.turtles.setDefault('atEdge', 'OK')

Here's an old demo with the above added. (The run() wrapper function is from pre-toplevel await, don't think it's needed now)
```
import * as util from '../src/utils.js'
import ThreeDraw from '../src/ThreeDraw.js'
import Model from '../models/Hello3DModel.js'

async function run() {
    const model = new Model()
    await model.startup()
    model.setup()

    model.turtles.setDefault('atEdge', 'OK')

    // defalt drawOptions!
    const view = new ThreeDraw(model, { div: 'modelDiv' })

    await util.timeoutLoop(
        () => {
            model.step()
            view.draw()
        },
        500,
        33
    )

    view.idle()
}
run()
```

Let me know if this solves your problem. 

And naturally we may need some modifications for these liberated turtles due to their not having an associated patch.
