### ISSUE TITLE
Compatible node versions?

### ISSUE THREAD

**Issue by byronrthomas** [backspaces/agentscript#92]
Hi, I would love to start playing with agentscript locally. Since many of the build / run etc scripts require node, I was wondering which node versions are you compatible with? I was hoping there might be a .node-version or .nvmrc or similar in this repo but I couldn't find one, and I also didn't see a mention of the compatible node versions.. (apologies if I missed it)

Thanks very much for making this available, looking forward to having a good play with it, it looks like a good project.

All the best,

Byron

**Comment by backspaces** [comment]
Hi! Glad to have you aboard!

Here are my current versions:
 git 2.30.1 (Apple Git-130)
 node v20.9.0
 npm 10.1.0
 npx 10.1.0
 yarn 1.22.19
 deno 1.39.0
I'm trying to use deno where it makes sense due to it using "browser javascript" rather than node's apis

The package.json has all the scripts used to build AS using "npm run <script name>"
There are some scripts that no longer work, I'll try to clean things up.

I just tried downloading and, assuming git & node installed, did this (mac os ventura):
github: download zip (green button) into downloads folder.
downloads: agentscript-master.zip
unzip (double click) in finder (/usr/bin/unzip would likely work too)

in terminal:
cd agentscript-master
yarn init (our team uses yarn, npm/node should work fine too)
yarn
npm run build

try it:
run all 2D demos in chrome: npm run run2 (gets favicon.ico errors, can ignore)

The usual "npm run start" starts a local server for exploring the repo.

Lets see if this works for you. If so, I'll add it to the docs. And thanks for getting involved!

**Comment by backspaces** [comment]
Oh and I forgot: the docs. We've just completed our tutorials. Try:
https://code.agentscript.org/docs/
Or if you have run start above, just navigate to docs.

Let me know if you spot problems.

**Comment by byronrthomas** [comment]
Awesome thanks, that's definitely working for me (using node v20).
